version: "3"
services:
  propile:
    build: .
    hostname: propile
    ports:
      - "3000:3000"
    environment:
      - RAILS_ENV=development
      - RECAPTCHA_SITE_KEY
      - RECAPTCHA_SECRET_KEY
    volumes:
      - data:/app/data
      - logs:/app/log
volumes:
  data:
  logs:
