development:
  adapter: postgresql
  encoding: unicode
  database: <%= ENV[ 'PROPILE_DEV_DB_NAME' ] %>
  pool: 5
  username: <%= ENV[ 'PROPILE_DEV_DB_USER' ] %>
  password: <%= ENV[ 'PROPILE_DEV_DB_PASS' ] %>

test:
  adapter: postgresql
  encoding: unicode
  database: <%= ENV[ 'PROPILE_TEST_DB_NAME' ] %>
  pool: 5
  username: <%= ENV[ 'PROPILE_TEST_DB_USER' ] %>
  password: <%= ENV[ 'PROPILE_TEST_DB_PASS' ] %>

production:
  adapter: postgresql
  encoding: unicode
  database: <%= ENV[ 'PROPILE_PROD_DB_NAME' ] %>
  pool: 5
  username: <%= ENV[ 'PROPILE_PROD_DB_USER' ] %>
  password: <%= ENV[ 'PROPILE_PROD_DB_PASS' ] %>
