version: "3"
services:
  haproxy:
    image: westghost/haproxy:0.1
    hostname: haproxy
    ports:
      - "80:80"
      - "8080:8080"
  propile_prod:
    image: westghost/propile:0.4.53
    hostname: propile_prod
    ports:
      - "3000:3000"
    environment:
      - RAILS_ENV=production
      - RECAPTCHA_SITE_KEY
      - RECAPTCHA_SECRET_KEY
      - SES_SMTP_USER
      - SES_SMTP_PASS
    volumes:
      - prod_data:/app/data
      - prod_logs:/app/log
  propile_test:
    image: westghost/propile:0.4.53
    hostname: propile_test
    ports:
      - "3002:3000"
    environment:
      - RAILS_ENV=production
      - RECAPTCHA_SITE_KEY
      - RECAPTCHA_SECRET_KEY
      - SES_SMTP_USER
      - SES_SMTP_PASS
    volumes:
      - test_data:/app/data
      - test_logs:/app/log
volumes:
  prod_data:
  prod_logs:
  test_data:
  test_logs:
