require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe PresentersController do

  # This should return the minimal set of attributes required to create a valid
  # Presenter. As you add validations to Presenter, be sure to
  # update the return value of this method accordingly.
  def valid_attributes
    {}
  end
  
  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # PresentersController. Be sure to keep this updated too.
  def valid_session
    {}
  end

  describe "GET index" do
    it "assigns all presenters as @presenters" do
      presenter = Presenter.create! valid_attributes
      get :index, {}, valid_session
      assigns(:presenters).should eq([presenter])
    end
  end

  describe "GET show" do
    it "assigns the requested presenter as @presenter" do
      presenter = Presenter.create! valid_attributes
      get :show, {:id => presenter.to_param}, valid_session
      assigns(:presenter).should eq(presenter)
    end
  end

  describe "GET new" do
    it "assigns a new presenter as @presenter" do
      get :new, {}, valid_session
      assigns(:presenter).should be_a_new(Presenter)
    end
  end

  describe "GET edit" do
    it "assigns the requested presenter as @presenter" do
      presenter = Presenter.create! valid_attributes
      get :edit, {:id => presenter.to_param}, valid_session
      assigns(:presenter).should eq(presenter)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new Presenter" do
        expect {
          post :create, {:presenter => valid_attributes}, valid_session
        }.to change(Presenter, :count).by(1)
      end

      it "assigns a newly created presenter as @presenter" do
        post :create, {:presenter => valid_attributes}, valid_session
        assigns(:presenter).should be_a(Presenter)
        assigns(:presenter).should be_persisted
      end

      it "redirects to the created presenter" do
        post :create, {:presenter => valid_attributes}, valid_session
        response.should redirect_to(Presenter.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved presenter as @presenter" do
        # Trigger the behavior that occurs when invalid params are submitted
        Presenter.any_instance.stub(:save).and_return(false)
        post :create, {:presenter => {}}, valid_session
        assigns(:presenter).should be_a_new(Presenter)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        Presenter.any_instance.stub(:save).and_return(false)
        post :create, {:presenter => {}}, valid_session
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested presenter" do
        presenter = Presenter.create! valid_attributes
        # Assuming there are no other presenters in the database, this
        # specifies that the Presenter created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        Presenter.any_instance.should_receive(:update_attributes).with({'these' => 'params'})
        put :update, {:id => presenter.to_param, :presenter => {'these' => 'params'}}, valid_session
      end

      it "assigns the requested presenter as @presenter" do
        presenter = Presenter.create! valid_attributes
        put :update, {:id => presenter.to_param, :presenter => valid_attributes}, valid_session
        assigns(:presenter).should eq(presenter)
      end

      it "redirects to the presenter" do
        presenter = Presenter.create! valid_attributes
        put :update, {:id => presenter.to_param, :presenter => valid_attributes}, valid_session
        response.should redirect_to(presenter)
      end
    end

    describe "with invalid params" do
      it "assigns the presenter as @presenter" do
        presenter = Presenter.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        Presenter.any_instance.stub(:save).and_return(false)
        put :update, {:id => presenter.to_param, :presenter => {}}, valid_session
        assigns(:presenter).should eq(presenter)
      end

      it "re-renders the 'edit' template" do
        presenter = Presenter.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        Presenter.any_instance.stub(:save).and_return(false)
        put :update, {:id => presenter.to_param, :presenter => {}}, valid_session
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested presenter" do
      presenter = Presenter.create! valid_attributes
      expect {
        delete :destroy, {:id => presenter.to_param}, valid_session
      }.to change(Presenter, :count).by(-1)
    end

    it "redirects to the presenters list" do
      presenter = Presenter.create! valid_attributes
      delete :destroy, {:id => presenter.to_param}, valid_session
      response.should redirect_to(presenters_url)
    end
  end

end
